<?php

namespace desplayBundle\Repository;

/**
 * costRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class costRepository extends \Doctrine\ORM\EntityRepository
{
}
