<?php

namespace desplayBundle\Repository;

/**
 * peopleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class peopleRepository extends \Doctrine\ORM\EntityRepository
{
}
