email:
    resource: "@emailBundle/Controller/"
    type:     annotation
    prefix:   /


desplay:
    resource: "@desplayBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

